apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: example-provider-secret
type: Opaque
data:
  orgToken: BASE64ENCODED_PROVIDER_CREDS
  userToken: BASE64ENCODED_PROVIDER_CREDS
---
apiVersion: mend.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  serverUrl: https://whitesource.mend.foo.bar/api/v1.3
  timeout: 3s
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: provider-mend
      key: none